title: victryx.github.io

description: >- 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  victryx

# Build settings
theme: jekyll-theme-console
plugins:
  - jekyll-feed
markdown: kramdown

defaults:
  - 
    scope: 
      path: ""
      type: "posts" # all files in _posts/ will have these defaults
    values: 
      layout: "post"

header_pages:
  - index.md
  - about.md
  - blog.md

style: dark
footer: '<a href="https://github.com/victryx/victryx.github.io">source code</a> ♥'

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
